# This Dockerfile governs the uPortal Demo Docker image.  The portal must be fully assembled
# (based on tomcatInstall + tomcatDeploy) before building the Docker image.

# Images built with the uPortal Gradle CLI may not be based on the :latest tag
ARG uPortalCliTag=latest

# This image requires Gradle;  it is not as slim as the web server-only image
FROM apereo/uportal-cli:$uPortalCliTag

# TCP traffic from this image is available on port 8080 (in case the Tomcat instance is started)
EXPOSE 8080

# Add Nano editor
RUN apk add nano

# Add MySQL client for database debugging
RUN apk add mysql-client

# Add Bind-tools and Nmap for network debugging
RUN apk add bind-tools
RUN apk add nmap
RUN apk add nc

ENTRYPOINT ["/bin/sh"]